-- MySQL Script generated by MySQL Workbench
-- Fri Dec  8 14:33:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema travlendarDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema travlendarDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travlendarDB` DEFAULT CHARACTER SET utf8 ;
USE `travlendarDB` ;

-- -----------------------------------------------------
-- Table `travlendarDB`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`User` (
  `IdUser` INT NOT NULL AUTO_INCREMENT,
  `eMail` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `UserResidence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travlendarDB`.`UserPreference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`UserPreference` (
  `IdUser` INT NOT NULL,
  `TakeCar` TINYINT NOT NULL,
  `TakeBus` TINYINT NOT NULL,
  `TakeCarSharing` TINYINT NOT NULL,
  `TakeBikeSharing` TINYINT NOT NULL,
  `MaxWalk` INT NOT NULL,
  `HasSeasonTicket` TINYINT NOT NULL,
  PRIMARY KEY (`IdUser`),
  CONSTRAINT `IdUserPrefTab`
    FOREIGN KEY (`IdUser`)
    REFERENCES `travlendarDB`.`User` (`IdUser`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travlendarDB`.`Ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`Ticket` (
  `IdTicket` INT NOT NULL,
  `IdUser` INT NOT NULL,
  `AvailableTicket` INT NOT NULL,
  PRIMARY KEY (`IdTicket`),
  INDEX `IdUser_idx` (`IdUser` ASC),
  CONSTRAINT `IdUserTicketTable`
    FOREIGN KEY (`IdUser`)
    REFERENCES `travlendarDB`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travlendarDB`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`Task` (
  `IdTask` INT NOT NULL,
  `IdUser` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(45) NULL,
  `Latitude` FLOAT NOT NULL,
  `Longitude` FLOAT NOT NULL,
  `Duration` INT NOT NULL,
  `StartTime` INT NULL,
  `EndTime` INT NULL,
  `StartDay` INT NULL,
  `EndDay` INT NULL,
  `isBreakTask` TINYINT NULL,
  `isPeriodic` TINYINT NOT NULL,
  `DayPeriodicity` INT NOT NULL,
  PRIMARY KEY (`IdTask`),
  INDEX `IdUser_idx` (`IdUser` ASC),
  CONSTRAINT `IdUserTaskTable`
    FOREIGN KEY (`IdUser`)
    REFERENCES `travlendarDB`.`User` (`IdUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travlendarDB`.`TaskPreference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`TaskPreference` (
  `IdTask` INT NOT NULL,
  `TakeCar` TINYINT NOT NULL,
  `TakeBus` TINYINT NOT NULL,
  `TakeCarSharing` TINYINT NOT NULL,
  `TakeBikeSharing` TINYINT NOT NULL,
  `MaxWalk` INT NOT NULL,
  PRIMARY KEY (`IdTask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travlendarDB`.`Travel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`Travel` (
  `IdTravel` INT NOT NULL,
  `IdStartTask` INT NOT NULL,
  `IdDestinationTask` INT NOT NULL,
  `StartPointLatitude` INT NOT NULL,
  `StartPointLongitude` INT NOT NULL,
  `EndPointLatitude` INT NOT NULL,
  `EndPointLongitude` INT NOT NULL,
  `TransportMean` VARCHAR(45) NOT NULL,
  `Duration` INT NOT NULL,
  PRIMARY KEY (`IdTravel`),
  INDEX `IdTaskStart_idx` (`IdStartTask` ASC),
  INDEX `IdTaskDestination_idx` (`IdDestinationTask` ASC),
  CONSTRAINT `IdStartTaskTravelTab`
    FOREIGN KEY (`IdStartTask`)
    REFERENCES `travlendarDB`.`Task` (`IdTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdDestinationTaskTravelTab`
    FOREIGN KEY (`IdDestinationTask`)
    REFERENCES `travlendarDB`.`Task` (`IdTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travlendarDB`.`Calendar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `travlendarDB`.`Calendar` (
  `IdUser` INT NOT NULL,
  `IdTask` INT NOT NULL,
  `StartDate` INT NOT NULL,
  `EndDate` INT NOT NULL,
  `StartTime` INT NOT NULL,
  `EndTime` INT NOT NULL,
  PRIMARY KEY (`IdUser`),
  INDEX `idTask_idx` (`IdTask` ASC),
  CONSTRAINT `idTaskClaendarTable`
    FOREIGN KEY (`IdTask`)
    REFERENCES `travlendarDB`.`Task` (`IdTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
